<?php
/**
* @file
* Let user change their password in Sonis.
*
* Let user change their password in Sonis password and check if user
* set exist in SONIS.
*/


/**
 * Implement hook_password_changer_api_check_user
 */

function password_changer_sonis_password_changer_api_check_user($user_name) {

  //Make sonis call to userExist in SONIS
  $results = sonisweb_integration_api("SonisWeb200.CustomPages.password_changer", "userExist", "yes",
                                     array(array('user_name', $user_name)));
  //If results is True return TRUE
  if ($results == 'True') {
    
    return TRUE;
  } //If results is False return FALSE
  elseif ($results == 'False') {
    
    return FALSE;
  }//If  not False and not True there is an error in coldfuncion funciton and return TRUE
  else {
    
    watchdog('[password_changer_sonis_module][_api_check_user]', 'SONIS is throwing an error.', WATCHDOG_ERROR);
    return FALSE;
  }
  
}

/*
 *Implement hook password_changer_api_change_password
 *From the password changer API
 */

function password_changer_sonis_password_changer_api_change_password($credentials) { 
 
  //Make sonis call to userExist in SONIS
  $results = sonisweb_integration_api("SonisWeb200.CustomPages.password_changer", "changePassword", "yes",
                                     array(array('user_name',  $credentials['user_name']),
                                           array('new_password', $credentials['password'])));
  
  //If results is True return TRUE
  if ($results == 'True') {
    
     return password_changer_api_status(array('status' => 'status',
                                             'message' => 'Password has been change in SONIS.'));
  } //If results is False return FALSE
  elseif ($results == 'False') {
    
    return password_changer_api_status(array('status' => 'error',
                                             'message' => 'Password has not been change in SONIS.'));
  }//If  not False and not True there is an error in coldfuncion funciton and return TRUE
  else {
    
    watchdog('[password_changer_sonis_module][_change_password]', 'SONIS is throwing an error.', WATCHDOG_ERROR);
    
    return password_changer_api_status(array('status' => 'error',
                                             'message' => 'Password has not been change in SONIS, their is an error in the SONIS call.'));
  }
  
}

/**
 * Implement hook_help()
 */
/*
function password_changer_sonis_help($path, $arg) {
  switch ($path) {
    case 'admin/help#password_changer_angel':
      $output = '<p>' . t('Just testing help hook') . '</p>';
      return $output;
  }
}
*/